### PR TITLE
Remove makedeps

### PR DESCRIPTION
**Pull request by doublec**
Removes the use of 'makeDeps' to generate include files and precompiled headers. Adds the required includes to the `.cpp` files. This makes dependencies  when using `make` and other tools a bit easier. It removes a build step. It allows editing header files and doing minimal builds without having to redo the header generation step and rebuild the world. Iterative development is faster and avoids the "Did I regenerate the include files?" questions when tracking down errors in development.

It's quite an invasive change though so I understand if it's not merged but I wanted to put it out there. I've been using it for a couple of years with a linux Makefile (instead of CMake) but I've just now made the changes to get it working with CMake so I could contribute it.

### CODE REVIEW

**Comment by doublec** [comment]
I'm investigating the Mac OS X Travis CI failures.

**Comment by doublec** [comment]
Latest commit fixes the travis ci error on Mac OS X.

**Comment by russellallen** [comment]
What are we losing by doing this? i.e. what was makedeps giving us that we're giving up?

**Comment by doublec** [comment]
From what I could tell, makedeps allowed generating an efficient set of include headers for c++ files that were optimal for precompiled header generation. There's an 'includeDB' file which contained a database of headers needed for each program and it analysed that, produced the needed '#include` statements in the right order, and a dependency file for 'Make' to use. The downside is needing to maintain `includeDB` and regenerating the headers whenever the original includes were changed.

CMake already handles the dependencies so we don't need that aspect of it. Modern g++/clang can also generate dependencies automatically if using normal Make files (I have an example Makefile for linux that does this for building Self).

I think what makedeps provided was making up for lack of tooling at the time it was written and it's no longer the case.

**Comment by davidungar** [comment]
Makedeps was originally put in for a good reason. Something about modularity and ability to evolve the VM.

I never liked the addition of cmake, btw, but I didn’t have to get the thing to build on other platforms, just
SunOS, Solaris, and OSX.

- David

**Comment by krono** [comment]
I advocated removing `makeDeps` once in 2012. It was strongly opposed as it reduced the build time somewhat. So it stayed.

But things like the threshold make it hard to manage: (see  3fa3ca009bbdf8729fefc3d72e3e6049e50bc990) …

**Comment by krono** [comment]
It even had the `#pragma once` already: 921379c609efa85c326bf5b7756fd12c3f4c4a85

**Comment by russellallen** [comment]
I think Self-the-open-source-project has somewhat different constraints to Self-the-Sun-project. Specifically our 'unusualness' budget is limited because it is much more important to be easy to get started from scratch without handholding. 

When I initially got David's linux port working it was very painful in part because I didn't know what the build story was. We're much more approachable now.

My concern is that although makedeps may give some advantage, the number of people who can take advantage of that advantage is currently nil.

On the plus side, removing makedeps makes the VM just that little bit more approachable, and maybe therefore more likely to be maintainable with the resources we have? This is the same sort of tradeoff as adopting cmake.

(On the other hand, we will need to get off this VM at some point because I can't see us getting to 64bit or multicore from here. The http://som-st.github.io stuff is very interesting esp TruffleSOM)

**Comment by doublec** [comment]
The goal of my recent pull requests, (fix warning messages and remove makeDeps), was to make working on the VM easier towards getting a 64bit port going. My tentative plan/approach is:

* Fix warnings
* Remove makeDeps to make working on the VM easier. I tried without doing this and was hitting issues where 'makeDeps' wasn't rerun so the CPP files were pulling in old header files. I'd already removed makeDeps for other reasons when I ported to using a Makefile on Linux so I moved that forward to CMake in this pull request.
* Work towards getting the VM 64 bit clean and building on 64 bit. It won't run due to lack of JIT code.
* Maybe get the interpreter working in the VM (I don't know the actual state of this other than there is some code there if SIC_COMPILER and NIC_COMPILER aren't defined). This would allow testing the 64bit VM without needing to write the JIT.
* Get an x86_64 NIC up and running.

Maybe some code cleanup/documentation on the way to getting the code 64 bit clean. This would probably need some discussion over what version of C++ to use - would introducing some C++11 libraries be problematic for example.

I also think an alternative VM like your TruffleSOM idea is also good project since multicore is unlikely with the current VM.

**Pull request merged**
