### PR TITLE
ePub/PDF improvements of handbook

### PR DESCRIPTION
**Pull request by Bystroushaak**
This pull request contains a lot of changes, which are mostly cosmetic, but because they were related to tabs/whitespaces, it appears that a lot of the handbook was changed. It really wasn't.

So, the changes:

- A lot of small bugfixes (dots, formatting, removed random appearances of † character).

- Removed sizes and align options from figures. PDF figures are now automatically centered, which looks better, HTML still aligned to left.

- Fixed Figure descriptions.
  snimek obrazovky-selfhandbook pdf-3

  vs

  snimek obrazovky-selfhandbook pdf-2

- Fixed references to tables and figures - because there was a lot of text-only references like Figure 5, which I changed to actual hyperlink references to images/tables, which won't break, when the new table/figure is added.

- This required to turn on numref (numeric references to tables/figures), so don't forget to update to newest version of Sphinx, or the references to figures will break.

- Table descriptions which were just bold text before table changed to actual sphinx table descriptions. This really helps in PDF, where the latex render too much often put the description on one page and table on second:

  snimek obrazovky-selfhandbook pdf

  vs

  snimek obrazovky-selfhandbook pdf-1

  This is little bit uglier in HTML version, but much more readable in PDF/ePub.

- A lot of textual description links to other sections (for example `See 3.4`) changed to hyperlinks.

- Fixed image sizes in PDF, added forced newpage latex commands. This is much saner now.

- Fixed code examples to use space indentation instead of tabs. This is really important for ebook readers/ePub, where the tab characters were so long, that almost every code example get out of the screen and it was really a pain to try to read the manual on ebook reader.

Here are the files available for inspection:

- http://kitakitsune.org/bhole/Self

It is not perfect, but much better than before. ePub version generated by sphinx is somehow a little bit broken, so you have to use calibre convertor to fix it for you (linked version is fixed).

I am now in the middle of the handbook, so there may be a little bit more fixes, but I don't expect nothing as big as this pull request :)

### CODE REVIEW

**Comment by russellallen** [comment]
Hi, this looks like good work but I can't access your http://kitakitsune.org/bhole/Self site? (Gives me 404)

**Comment by Bystroushaak** [comment]
Sorry, I was just tunning the webserver. It should work now.

**Comment by russellallen** [comment]
Hi, sorry still can't access PDF or epub?

**Comment by Bystroushaak** [comment]
What is the message? Please try the URL with / at the end http://kitakitsune.org/bhole/Self/

There should be 302/303 redirect to URL with slash, but if your browser doesn't support it..

**Comment by russellallen** [comment]
I can see the index page but the actual PDF and epubs give me a 404

**Comment by Bystroushaak** [comment]
Okay, I will reupload them. Mmnt.

**Comment by Bystroushaak** [comment]
Here:

- https://dl.dropboxusercontent.com/u/11891854/tmp/ebooks/Self/SelfHandbook.epub
- https://dl.dropboxusercontent.com/u/11891854/tmp/ebooks/Self/SelfHandbook.pdf

**Comment by russellallen** [comment]
Cool, thanks.

**Pull request merged**
